### ISSUE TITLE
Helm wrong templating for node.yaml tolerations

### ISSUE THREAD

**Issue by apt-x4869** [outscale/osc-bsu-csi-driver#967]
/kind bug

**What happened?**
Incorrect template is generated using the latest helm chart 1.7.2 :

```
    tolerations
        - key: CriticalAddonsOnly
          operator: Exists
        - operator: Exists
          effect: NoExecute
          tolerationSeconds: 300        - key: test.com/arch
          operator: Exists
        - key: test.com/gpu
          operator: Exists
        - key: test.com/group
          operator: Exists
```

**What you expected to happen?**
Expected below output

```
    tolerations
        - key: CriticalAddonsOnly
          operator: Exists
        - operator: Exists
          effect: NoExecute
          tolerationSeconds: 300        
        - key: test.com/arch
          operator: Exists
        - key: test.com/gpu
          operator: Exists
        - key: test.com/group
          operator: Exists
```

**How to reproduce it (as minimally and precisely as possible)?**
Add below to values.yaml :
```
node:
  tolerateAllTaints: false
  tolerations:
    - key: test.com/arch
      operator: Exists
    - key: test.com/gpu
      operator: Exists
    - key: test.com/group
      operator: Exists
````
Run below command:
`kubectl template test osc-bsu-csi-driver-1.7.2.tgz --debug -f values.yaml`

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:
